theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dirt"
title: "WisigothExOriente's page | Portfolio"
description: stuff.
author: WisigothExOriente
url: "https://wisigothexoriente.github.io"
baseurl: "" 
